#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-21"
pages_build_output_dir = "./build/client"
send_metrics = false
